### ISSUE TITLE
How to deploy API project on CentOS?

### ISSUE THREAD

**Issue by onetechwolf** [onetechwolf/salon-flutter-angular-laravel#1]
API Project is made in Laravel language. I'm gonna deploy on CentOS and tried to deploy many times.
but I've always encountered in cors problem.
How can I fix it?

**Comment by muradalidev** [comment]
You should use laravel install wizard. 
This will help you. https://laravel-news.com/laravel-setup-wizard
hope this will be helpful for you. :)

**Comment by onetechwolf** [comment]
Great. I fixed my issue by referencing https://laravel-news.com/laravel-setup-wizard.
Thanks muradalidev. 👍
